### ISSUE TITLE
Floating point

### ISSUE THREAD

**Issue by jedbrown** [nnethercote/perf-book#11]
It would be useful to discuss ways of enabling fused multiply-add instructions (like `-ffp-contract=fast` for gcc/clang) and dropping strict associativity in reductions (to enable multiple accumulators in sums, which is necessary for vectorization and ILP).

**Comment by nnethercote** [comment]
Thanks for the suggestion.

I'm trying to keep the book practical by focusing on techniques that have been shown to be useful on real code. Do you have examples where these techniques led to speed-ups in programs?

Also, I don't know how to actually do these things in Rust. Can you explain, or link to instructions that explain?

**Comment by jedbrown** [comment]
Darn, I was kinda hoping you would know tricks to improve ergonomics. :smile: 

This is an example showing how C produces vectorized code with multiple accumulators and all the arithmetic done with FMA instructions on AVX registers (8 flops/instruction, with extra unrolling to cover instruction latency). The corresponding Rust uses only scalar instructions, uses separate adds and multiplies, and does not reorder the summation so it does only one flop per instruction and needs to wait for the 3-5 cycle instruction latency.

https://godbolt.org/z/n6bMrj

Real-world examples where these sort of differences matter are a dime a dozen in numerical/scientific computing. I've run into some Rust packages that produce fast numerical code (e.g., https://github.com/bluss/matrixmultiply) but they seem to drop to intrinsics much sooner than is needed in C. There is a [portable SIMD working group](https://blog.rust-lang.org/inside-rust/2020/09/29/Portable-SIMD-PG.html) that will make intrinsics more convenient, but it still isn't vectorizing well-written generic code in the way C programmers expect.

**Comment by nnethercote** [comment]
So, this is far beyond what either of us knows about, which means there's no real path forward for this issue. So I will close it. Maybe someone who knows more about this will come along with more info at some point.
