### ISSUE TITLE
What are the downsides of the `Cow` type?

### ISSUE THREAD

**Issue by seanchen1991** [nnethercote/perf-book#12]
The section on `Cow` in the Heap Allocations chapter doesn't mention this. It would be useful to get a sense of the tradeoffs when using it.

**Comment by nnethercote** [comment]
The text currently says "Cow can be fiddly to get working, but it is often worth the effort."

Do you have any other specific downsides in mind?

**Comment by nnethercote** [comment]
I will close this. Please reopen if you have specifics in mind. Thanks.
