### ISSUE TITLE
Implication that only Intel CPUs support AES instructions

### ISSUE THREAD

**Issue by redzic** [nnethercote/perf-book#13]
On the [hashing page](https://nnethercote.github.io/perf-book/hashing.html), it states that `ahash` provides a hashing algorithm that can leverage the AES instruction set if the CPU supports it, but it says "on Intel processors", [even though Zen-based AMD processors (and others) support AES instructions](https://en.wikipedia.org/wiki/AES_instruction_set#AMD).

Instead, it should probably either just say "on CPUs that support AES instructions", or say "on some Intel and AMD processors".

**Comment by nnethercote** [comment]
Thanks for the suggestion!
