### ISSUE TITLE
Mention cranelift to reduce compile time?

### ISSUE THREAD

**Issue by FilipAndersson245** [nnethercote/perf-book#15]
Do  not know as of yet if you can change your toml file to use cranelift but should probably be mentioned whatever cranelift becomes available.

**Comment by nnethercote** [comment]
I deliberately left Cranelift unmentioned for now because it is experimental. Once it becomes a standard thing I am happy to add it. In the meantime, I'd rather not have an issue open that cannot be resolved, so I will close this.
