### ISSUE TITLE
Define "hot"

### ISSUE THREAD

**Issue by sburris0** [nnethercote/perf-book#21]
Am I correct in assuming that a "hot function" is one that is frequently called?
My second guess would be one that is computationally expensive, or both.
This is a new term for me and I haven't been able to find a definition anywhere, so clarification in the book would be greatly appreciated.

**Comment by wtklbm** [comment]
I also want to know

**Comment by cristaloleg** [comment]
> computationally expensive

AFAIR it's "heavy".

"hot function" is about "how many times it's called" (probably it goes from physics)

**Comment by nnethercote** [comment]
Thanks for the suggestion. I added a definition in [48075fe](https://github.com/nnethercote/perf-book/commit/48075fe9ff0080decc4b8e8928a86d8ef969901a).
