### ISSUE TITLE
Consider talking about platform support for tooling

### ISSUE THREAD

**Issue by djc** [nnethercote/perf-book#27]
In the profiling chapter (and maybe also when discussing DHAT in the allocations chapter) might be useful to discuss on what platforms the various tools are available. In particular, I do most of my development on macOS, so valgrind is often not available and perf, I think, also doesn't work. Instead you get things like Instruments (which I've briefly tried but didn't really help me when I did). flamegraph has dtrace support so also works on macOS (and possibly BSDs? might be too niche too spend words on).

**Comment by nnethercote** [comment]
Thanks for the suggestion.
