### ISSUE TITLE
Discuss Iterator trait implications for allocations?

### ISSUE THREAD

**Issue by djc** [nnethercote/perf-book#28]
Specifically how `Iterator::size_hint()` and `ExactSizeIterator` might affect `Vec` or `HashMap` growth. Also, how combinators like `filter()` or `map()` effect this.

**Comment by nnethercote** [comment]
I don't know anything about this topic. Can you explain some more? Would this go in the Heap Allocation chapter?

**Comment by djc** [comment]
Yes, I think it would go in the Heap Allocation chapter.

The way I understand it, the `size_hint()` method on `Iterator` helps code downstream of an `Iterator` to make larger allocations in advance according to the expected size of the iterator. This is particularly relevant for the `FromIterator` trait (and thus the `Iterator::collect()` method as well as the `Extend` trait and its implementers, where it can matter substantially to do one large allocation vs many increasingly larger ones as the iterator is emptied. Whereas `Iterator::size_hint()` gives an approximation, implementing the `ExactSizeIterator` basically gives callers a way to get the exact size of the iterator. `Iterator` combinators like `map()` should then preserve the `size_hint()`/`len()` information, while `filter()` or `filter_map()` would obviously not be able to.

Does that help?

Also, while giving feedback I neglected to mention that I think this is a very cool resource, thanks for bundling all this knowledge (and for your invaluable work on rustc performance and writing it up, of course)!

**Comment by nnethercote** [comment]
Thanks for the explanation. It could have gone in the Heap Allocations chapter, but the Iterators chapter already has stuff about `collect` and `extend` so I ended up putting it there.
