### ISSUE TITLE
Profiler for Windows

### ISSUE THREAD

**Issue by d00z3l** [nnethercote/perf-book#31]
The profiler page has no options for Windows. I have been using AMD uProf successfully with my Rust programs on Windows and would recommend it. It is also available for Linux.

https://developer.amd.com/amd-uprof/

**Comment by nnethercote** [comment]
Thanks for the suggestion. Does uProf only work with AMD processors?

**Comment by d00z3l** [comment]
No, it is a generic profiler. I am using with an Intel processor.

**Comment by d00z3l** [comment]
There aren't as many profiler options of Windows as Linux...
