### ISSUE TITLE
Should bytehound be included in the list of profilers?

### ISSUE THREAD

**Issue by saethlin** [nnethercote/perf-book#37]
https://github.com/koute/bytehound

The author says they've used it in production: https://www.reddit.com/r/rust/comments/p6nnk5/just_released_bytehound_07_a_memory_profiler_for/h9er0ep/
I haven't tried it out myself yet, so I can't attest at all to whether it's better than DHAT in any regard.

**Comment by nnethercote** [comment]
Sorry for the slow response, and thanks for the suggestion.
