### ISSUE TITLE
Add Instrument profiler for Mac

### ISSUE THREAD

**Issue by yvgny** [nnethercote/perf-book#39]
Hi all,

Firstly, thank you very much for your awesome work with this book, it's very useful ! 
I recently tried to profile my Rust program on Mac but the only proposed option was Flamegraph, which seems very nice but didn't quite fit what I was looking for (i.e not only generate a static image but being able to walk through the call tree, and so on). Finally I ended up using the profiler shipped with the Xcode developper tools called Instrument, and it did work very well with the Rust executable. Thus I believe that it might be a good addition to the list of profiler you have in the book. What do you think ?

Bests,
Sacha

**Comment by nnethercote** [comment]
Thanks for the suggestion. I have done this in https://github.com/nnethercote/perf-book/commit/094b3e33150631e10ac1531de3297b0d59d2dc24.
