### ISSUE TITLE
Some more topic ideas

### ISSUE THREAD

**Issue by najamelan** [nnethercote/perf-book#4]
- https://profiler.firefox.com/ is a very nice tool for [visualizing and sharing perf profiles](https://www.reddit.com/r/linux/comments/g0mx3z/til_firefox_profiler_makes_an_awesome_gui_for_perf/).
- https://deterministic.space/high-performance-rust.html seems to have some tips that aren't included in the book, like `-C target-cpu=native`, `codegen-units`, using a different allocator, etc...

**Comment by nnethercote** [comment]
Thanks for the suggestions.

I have added Firefox Profiler to the profilers section. I plan to include the things you mentioned from the high-performance-rust post, but I will do it separately from this issue because it's a bigger piece.
