### ISSUE TITLE
Mention nohash_hasher

### ISSUE THREAD

**Issue by Glitchy-Tozier** [nnethercote/perf-book#41]
[nohash_hasher](https://docs.rs/nohash-hasher/0.2.0/nohash_hasher/) seem to be an interesting replacement for HashMap/HashSet when using integers as keys.

**Comment by nnethercote** [comment]
Addressed [here](https://github.com/nnethercote/perf-book/commit/c30dcc00f96e3538d1cc1d01dadc861a71ffee5f). Thank you for the suggestion.

**Comment by Glitchy-Tozier** [comment]
Thank you for adding it.

I have one question: I have read a couple of times that [_under certain circumstances_](https://stackoverflow.com/questions/70554697/risks-in-using-nohashhasher) this the nohash_hasher might be slower than other implementations. However, I have not found any explanations for what those "certain circumstances" may be. Do you have any idea?

**Comment by nnethercote** [comment]
It's going to depend on the distribution of your keys, and how likely collisions are. That stackoverflow question has some discussion of this in the comments.
