### ISSUE TITLE
Possibly add `tinyset` to hashing-section

### ISSUE THREAD

**Issue by Glitchy-Tozier** [nnethercote/perf-book#42]
This `HashSet`-replacement (no `HashMap`, it seems like) sounds like it could be interesting: https://docs.rs/tinyset/latest/tinyset/index.html

Unfortunately, I don't have the expertise to know in which cases it will perform better/worse than other `HashSet`s and what risks are associated with it.

**Comment by nnethercote** [comment]
Thanks for the suggestion. I think this is a bit too niche to be worth mentioning.
