### ISSUE TITLE
Collections: accessing `&mut [T]` is faster than `Vec<T>`

### ISSUE THREAD

**Issue by Shnatsel** [nnethercote/perf-book#50]
`&mut [T]` provides aliasing information to the compiler - it guarantees that nothing else is going to access the data while this borrow is alive. This allows the compiler to eliminate redundant loads from memory to a register.

By contrast, `Vec<T>` does not provide such guarantees. 

It is therefore beneficial to pass around `&mut [T]` instead of `Vec<T>` whenever possible.

I've sped up the `fastblur` crate by 15% simply by converting the type a function accepts from `&mut Vec<T>` to `&mut [T]`: https://github.com/fschutt/fastblur/pull/3

---

Aliasing aside, the compiler also infers that the slice is fixed-size, and this may let it eliminate the bounds checks. The same information is not conveyed by a Vec. Because of that, it can be useful to convert a Vec to a mutable slice before indexing into it a lot, even ignoring the aliasing guarantees. 

Examples:

Vec: https://github.com/Shnatsel/bounds-check-cookbook/blob/main/src/bin/fibvec_naive_indexing.rs

Vec converted to a slice before a hot loop: https://github.com/Shnatsel/bounds-check-cookbook/blob/main/src/bin/fibvec_clever_indexing.rs

**Comment by nnethercote** [comment]
> `&mut [T]` provides aliasing information to the compiler - it guarantees that nothing else is going to access the data while this borrow is alive. This allows the compiler to eliminate redundant loads from memory to a register.
> 
> By contrast, `Vec<T>` does not provide such guarantees.
> 
> It is therefore beneficial to pass around `&mut [T]` instead of `Vec<T>` whenever possible.

I'm confused by this.
- First, I think you mean "pass around `&mut [T]` instead of `&mut Vec<T>` whenever possible", right?
- Second, doesn't the "nothing else is going to access the data" condition also hold for `&mut Vec<T>`? I think the real cause of the speedup would be that `&mut [T]` provides a direct pointer to the elements. Whereas `&mut Vec<T>` provides a pointer to the `Vec`, which contains a pointer to the elements, i.e. an extra pointer deref is required.

**Comment by Shnatsel** [comment]
> First, I think you mean "pass around &mut [T] instead of &mut Vec<T> whenever possible", right?

Yes, that is correct.

> Whereas &mut Vec<T> provides a pointer to the Vec, which contains a pointer to the elements, i.e. an extra pointer deref is required. (e.g. see the last paragraph of https://github.com/nnethercote/perf-book/issues/54#issuecomment-1383183653)

I've tried it in godbolt and that reasoning does seem to be correct: https://godbolt.org/z/5jK9vjh3f

I'm not sure if aliasing also plays a role. Dumping LLVM IR in playground didn't provide any clues. At any rate, avoiding double indirection still makes this pattern worthwhile.

**Comment by Shnatsel** [comment]
I got clarity on aliasing thanks to @saethlin:

https://godbolt.org/z/PazT7Gnf9 - Ctrl+F for `noalias`

> Both have `noalias`, but in the `Vec` example, the aliasing contract is about the bytes of the `Vec` itself not its allocation.

**Comment by Shnatsel** [comment]
Another benefit is that a `&mut [u8]` is fixed-length, unlike a `&mut Vec<u8>` that can be resized. The knowledge that the length if unchanging allows the compiler elide the bounds checks. I have examples showcasing this in my article:
https://shnatsel.medium.com/how-to-avoid-bounds-checks-in-rust-without-unsafe-f65e618b4c1e

So there are actually at least three different reasons why a slice is faster than a `Vec`:

1. Avoids double indirection on indexing
2. Aliasing guarantees
3. The optimizer has an easier time removing bounds checks

And this isn't limited to function arguments - it's a good idea to turn a `Vec<T>` into a `&mut [T]` before you index into it a lot.

**Comment by nnethercote** [comment]
Thanks for the extra info. I just learned that clippy's `ptr_arg` lint warns about `&Vec<T>`, `&mut Vec<T>`, and other similar types being used as function arguments. One of my goals with the book is to [keep it short[(https://github.com/nnethercote/perf-book/commit/e035422129902f006ed661e407c28ecb0db8290d), so I have decided I won't mention this or any other problems that clippy can catch. But I did end up mentioning the fastblur PR in the text in https://github.com/nnethercote/perf-book/commit/ead1d924cdca9e8c100248a5f7754e6441d98553.

**Comment by Shnatsel** [comment]
Clippy's warning doesn't describe any performance implications. I'll open an issue for Clippy to also describe them.

**Comment by Shnatsel** [comment]
I have realized that it's impossible to use Clippy to suggest this transformation for `&mut Vec<T>` because it would cause false positives if the `Vec` is being both indexed into and extended via `push()` and such.

So I believe the `&Vec<T>` case can be addressed by Clippy, but `&mut Vec<T>` should be called out in the book.

**Comment by nnethercote** [comment]
Clippy is smart enough to distinguish these cases. For this code:
```rust
fn foo1(x: &mut Vec<u32>) -> u32 { x[0] }

fn foo2(x: &mut Vec<u32>) -> u32 { x.push(1); x[0] }
```
it only warns about `foo1`:
```
warning: writing `&mut Vec` instead of `&mut [_]` involves a new object where a slice will do
 --> src/main.rs:7:12
  |
7 | fn foo1(x: &mut Vec<u32>) -> u32 { x[0] }
  |            ^^^^^^^^^^^^^ help: change this to: `&mut [u32]`
  |
  = note: `#[warn(clippy::ptr_arg)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
```
