### ISSUE TITLE
Iterators: recommend interior iteration - `iter.for_each()` instead of `for x in iter`

### ISSUE THREAD

**Issue by Shnatsel** [nnethercote/perf-book#51]
See e.g. https://github.com/rust-lang/rust/issues/101814

I recall encountering a case in the wild where `iter.for_each()` optimized better than `for x in iter`, but it's been a while and Github won't let me search my pull requests, so I cannot point to the specific instance of that.

**Comment by Shnatsel** [comment]
This article goes into more depth about the reasons behind it, and internal vs external iteration: 
https://medium.com/@veedrac/rust-is-slow-and-i-am-the-cure-32facc0fdcb

**Comment by nnethercote** [comment]
I've seen that article before and I find it confusing, specifically due to the update about `try_fold`. Does that update mean that external iteration is now just as fast as internal iteration?

**Comment by muskaantiwari** [comment]
`iter.for_each()` applies a closure to each element of the iterator, while `for x in iter` is a separate but straightforward implementation of a typical for loop.

Regarding performance, contrary to your (@Shnatsel) assertion, `for x in iter` is generally faster than `iter.for_each()` for some cases. Loop constructs are specially optimized by the compiler (e.g. loop unrolling) and are not specific to Rust. I vividly remember, they taught these optimizations in my compilers [course](https://www.geeksforgeeks.org/loop-optimization-in-compiler-design/). Again, the latter uses a closure, which introduces an overhead, which is usually small and will not be noticeable in most cases.

**Comment by nnethercote** [comment]
I'm going to close this due a lack of a clear recommendation.
