### ISSUE TITLE
Iterators: recommend the `chunks_exact` + `remainder` pattern

### ISSUE THREAD

**Issue by Shnatsel** [nnethercote/perf-book#52]
Currently the book recommends using `chunks_exact` if the slice divides by chunk size exactly. 

However, the `_exact` variant is useful even when they don't divide exactly, and provides a convenient way to handle the part that wasn't exact - `.remainder()`.

I now have real-world examples showing this pattern, where `chunks_exact` eliminates bounds checks and lets the compiler vectorize the code:

https://github.com/johannesvollmer/exrs/pull/173  - here the slice is iterated over using `chunks_exact` and the last element is handled manually

https://github.com/johannesvollmer/exrs/pull/175 - here one is vectorized and the other runs with instruction-level parallelism, still without bounds checks. Note the `remainder` handling at the end of these functions.

**Comment by nnethercote** [comment]
Done in https://github.com/nnethercote/perf-book/commit/6355dea41c86de86830c406aa90df83657eaee88. Thanks for the suggestion.
