### ISSUE TITLE
My question and doubt about "using CPU specific instructions"

### ISSUE THREAD

**Issue by SatinWuker** [nnethercote/perf-book#55]
I really enjoy using this project since it really did help me to improve my code efficiency. However I have a question on https://nnethercote.github.io/perf-book/build-configuration.html#using-cpu-specific-instructions
It mentions that `if you pass -C target-cpu=native to rustc, it will use the best instructions for your current CPU`
Yet I saw a Reddit post: https://www.reddit.com/r/rust/comments/hozs31/target_feature_vs_target_cpu_for_rust/
There is a comment that says "Note that target-cpu=native can degrade code performance, instead of improving it. I've seen it enough times to think that this option is somewhat broken. "
I am really bothered by this lol, I apologize for my ignorance 😆

**Comment by nnethercote** [comment]
Thanks for the suggestion. I added a warning about possible slowdowns at the top of that chapter, in https://github.com/nnethercote/perf-book/commit/c5018f228c01eaf80d7dcfd613c995681b27fea8.
