### ISSUE TITLE
Publish ePUB

### ISSUE THREAD

**Issue by mcandre** [nnethercote/perf-book#58]
Hi,

Solid content. I'd like to see an official ePUB generated, for easier reading on offline e-imk devices.

**Comment by nnethercote** [comment]
I tried to set this up, and it basically worked. But I hit a problem affecting the HTML version of the book, as described in this commit message where I disabled the ePub generation: https://github.com/nnethercote/perf-book/commit/5d37cf2d83e1583f193007c3dd0fd9314943a0ca

If you know of a workaround that would let me generate the ePub version while also keeping the HTML version URL unchanged, I'd love to hear it.

**Comment by nnethercote** [comment]
A couple of other notable things, which make the ePub version inferior to the HTML vrsion.
- I viewed the produced epub file in Books on Mac. The output quality is ok, but not great. In particular, some quite excessive amounts of whitespace.
- The book has a lot of links, which are hard to view on an e-ink device.

**Comment by nnethercote** [comment]
Based on the difficulties mentioned above, I will close this. I'd be happy to reconsider if solutions can be found.

**Comment by mcandre** [comment]
The mdbook behavior is unfortunate.

As a workaround, you could generate the ePUB locally.

Yes, some ePUB generators are awful about extraneous whitespace. I actually wrote a little CLI script to help clean up some common ePUB quirks like that:

https://github.com/mcandre/nile

Yes, links are often hard to view in ebooks and printed books. One solution is to always write URL's in tutorials out in plain long form, without using a shorter name descriptor. Then, every view of the URL is sure to show the full URL. URL simplification be done manually, or automated with some Markdown parser or some awk script.

An ePUB, with or without pretty URL's, is still more useful than no ePUB.

**Comment by nnethercote** [comment]
> As a workaround, you could generate the ePUB locally.

And commit it to the repository every time the text changes? I'm not willing to do that.

I view the HTML version as by far the most important, and I am willing to have an ePub version only if it doesn't negatively affect the HTML version. The whitespace and URL issues are unfortunate but not showstoppers. Changing the URL for the HTML book is a showstopper, alas.

**Comment by ehuss** [comment]
The URL shouldn't need to be changed.  I'm not familiar with the github actions you are using, but I suspect it just needs to change to something like adding this just before deploy:

```yaml
      - name: Add ePub
        run: cp book/epub/The\ Rust\ Performance\ Book.epub book/html
```

and changing the deploy directory to:

```yaml
          publish_dir: ./book/html
```
