### ISSUE TITLE
Expand chapter on LLVM IR

### ISSUE THREAD

**Issue by Boshen** [nnethercote/perf-book#60]
When I was studying about slow compile times in swc, I came across Aleksey's blog on this topic. He described in detail on [instantiations](https://matklad.github.io/2021/09/04/fast-rust-builds.html#Keeping-an-Eye-on-Instantiations). 

It was super useful for me because
1. he showed the `cargo-llvm-lines` output to demonstrate the exact problem on generics
2. he showed the `std::fs::read` snippet and describe what the `inner` function does, which I often wondered why when I was navigating the rustc source code.

So may I suggest to expand on this topic a little bit by showing some code snippets in the [LLVM IR chapter](https://github.com/nnethercote/perf-book/blob/master/src/compile-times.md#llvm-ir)? It didn't click for me the first few times I read it 😅

**Comment by nnethercote** [comment]
Thanks for the suggestion. I tried to strike a balance between being brevity and usefulness. https://github.com/nnethercote/perf-book/commit/65e242e9be8a7816e8f47160a47fa1ad57d72dd8 adds an example of an inner function. I don't want to include `cargo-llvm-lines` output, but https://github.com/dtolnay/cargo-llvm-lines/pull/68 may help on that front.
