### ISSUE TITLE
Inlining - None

### ISSUE THREAD

**Issue by Lokathor** [nnethercote/perf-book#61]
Under chapter 6 Inlining, it talks about inlining levels and says:

> None. The compiler will decide itself if the function should be inlined. This will depend on the optimization level, the size of the function, etc. If you are not using link-time optimization, functions will never be inlined across crates.

However, functions with generics will generally be inlined across crates even without the inline attribute. They're mono-morphized into the user's crate and then they can get "in the same crate" level inlining. (though i'm told that the share-generics can interfere with this.)

It think it's appropriate to mention generics *can* be inlined even without the inline attribute.

**Comment by nnethercote** [comment]
Fixed by https://github.com/nnethercote/perf-book/commit/85a3e529c3778242d431aaba21f7159093c6eb83. Thanks for the suggestion.
