### ISSUE TITLE
Mention Intel VTune Profiler

### ISSUE THREAD

**Issue by Gabaa** [nnethercote/perf-book#63]
Intel VTune Profiler could be added to the list of profilers. I've used it with Rust on Windows, but it should work on Linux too.

https://www.intel.com/content/www/us/en/developer/tools/oneapi/vtune-profiler.html

**Comment by nnethercote** [comment]
Fixed in https://github.com/nnethercote/perf-book/commit/6a0419c0d8d896998944d2da0c056164619e29c8, thanks for the suggestion.
