### ISSUE TITLE
"Machine code" section should suggest `cargo asm`

### ISSUE THREAD

**Issue by Shnatsel** [nnethercote/perf-book#64]
https://nnethercote.github.io/perf-book/machine-code.html mentions Compiler Explorer as a tool for inspecting assembly. It is very handy for snippets, but is impractical for inspecting the codegen of a given function in a large codebase, especially anything tightly coupled with the rest of the codebase (uses lots of custom types, etc).

I've found https://github.com/pacak/cargo-show-asm to be a very handy tool for inspecting the codegen for a given function, without having to extricate it from the codebase. The chapter should probably mention it as an option.

**Comment by bjorn3** [comment]
Note that cargo asm uses `--emit=asm` which forces a single codegen unit for back compat reasons and thus may affect optimizations.

**Comment by Shnatsel** [comment]
Yes. And it also disables LTO: https://github.com/pacak/cargo-show-asm/blob/0367ffdc0f84e91c21fe04d48c6cb9ad7a0f4e9a/src/main.rs#L92

But Godbolt also compiles the code in a single codegen unit, so at least it's no worse than Godbolt.

**Comment by pacak** [comment]
FWIW LTO hack was reverted in 0.2.22, but it should not affect the output as far as `--emit=asm` is concerned.

**Comment by nnethercote** [comment]
Done in https://github.com/nnethercote/perf-book/commit/3dc0a98387ac5cd93e3edbaa691e412662bd2b43, thanks for the suggestion.
