### ISSUE TITLE
Inlining: mention `missing_inline_in_public_items` Clippy lint

### ISSUE THREAD

**Issue by Shnatsel** [nnethercote/perf-book#65]
If your API consists of lots of small functions (e.g. a data structure implementation like `Vec`), it can be easy to forget to add `#[inline]` to a public item and make it non-inlineable across crate boundaries, leaving performance on the table in non-obvious ways.

Clippy [has a lint](https://rust-lang.github.io/rust-clippy/master/#/missing_inline_in_public_items) to help with this: adding `#![warn(clippy::missing_inline_in_public_items)]` to the top of the file or in `lib.rs` will trigger a warning when a public function doesn't have an `#[inline]` attribute. This can be disabled with `#[allow(clippy::missing_inline_in_public_items)]` on a per-file or per-function basis if needed.

**Comment by nnethercote** [comment]
Thanks for the suggestion. After some thought, I decided that this is obscure enough that I won't add it.
