### ISSUE TITLE
Inlining: mention that it is not transitive

### ISSUE THREAD

**Issue by Shnatsel** [nnethercote/perf-book#66]
One thing that surprised me about inlining is that the `#[inline]` attribute is not transitive. That is, if I have function `foo()` which calls `bar()` internally, and only `foo()` is annotated with `#[inline]`, then the contents of `foo()` can be inlined across crate boundary but its internal call to `bar()` will not.

Reference:

> Note that `#[inline]` is not transitive: if a trivial public function calls a trivial private function, you need to `#[inline]` both. See [this benchmark](https://github.com/matklad/benchmarks/tree/91171269f0a6e260a27111d07661021a89d20085/rust-inline) for details.

from https://matklad.github.io/2021/07/09/inline-in-rust.html

**Comment by nnethercote** [comment]
Fixed in https://github.com/nnethercote/perf-book/commit/381e7f693e4afd171df6a19966e957006f98c957, thanks!
