### ISSUE TITLE
Add Intel Vtune as another option for Profiling

### ISSUE THREAD

**Issue by stevenhuyn** [nnethercote/perf-book#74]
Hey was wondering if it's cool to add Intel Vtune as a Windows friendly option for profiling?
https://www.intel.com/content/www/us/en/developer/tools/oneapi/vtune-profiler.html

To add onto this page: https://nnethercote.github.io/perf-book/profiling.html

My install of [AMD μProf](https://developer.amd.com/amd-uprof/) broke and there is literally not another Windows option in that list lol.

**Comment by nnethercote** [comment]
Have you successfully used Vtune on Rust code? I'm happy to add it if so.

**Comment by stevenhuyn** [comment]
Yup worked perfect! Got flamegraph, bottom up, top down views.

**Comment by stevenhuyn** [comment]
![image](https://github.com/nnethercote/perf-book/assets/18359644/90e27944-d194-4252-846a-f9ce7ffed1ea)

**Comment by stevenhuyn** [comment]
Lmao it's already there oops!

https://github.com/nnethercote/perf-book/commit/6a0419c0d8d896998944d2da0c056164619e29c8
