### ISSUE TITLE
A little more on Parallelization

### ISSUE THREAD

**Issue by lukesdm** [nnethercote/perf-book#9]
As noted in the 'Parallelism' chapter, parallelization can be a source of huge performance gains. It might be worth mentioning that it depends heavily on the application's design, but the gains can make it worth considering before introducing fine-tuned optimizations. And maybe point out where sometimes these can make it more difficult to parallelize, e.g. the 'workhorse collections', where a mutable data structure is introduced. OTOH, maybe anyone reading this is likely to know which optimizations are parallel friendly?

**Comment by nnethercote** [comment]
I mentioned the design part, though I didn't mention the more-difficult-to-parallelize part, because it seemed like too much detail.

Thanks for the suggestion.
